crm/urls.py
from django.conf.urls import url
from crm import campaign

app_name = "crm"

urlpatterns = [

    url(r'^campaign/create/$', campaign.campaign_create, name="campaign_create"),
    url(r'^campaign/list/$', campaign.campaign_list, name="campaign_list"),
    url(r'^campaign/(?P<pk>[^/]+)/detail/$', campaign.campaign_detail, name="campaign_detail"),
    url(r'^campaign/(?P<pk>[^/]+)/edit/$', campaign.campaign_edit, name="campaign_edit"),
    url(r'^campaign/(?P<pk>[^/]+)/list_products/$', campaign.products, name="products"),


]

enquiry/urls.py
from django.conf.urls import url
from enquiry import views, enquiry


app_name = "enquiry"

urlpatterns = [
    url(r'^enquiries/$', enquiry.list, name="list"),
    url(r'^enquiries/lead/$', enquiry.mylist, name="mylist"),
    url(r'^enquiries/walkins/$', enquiry.walkinList, name="walkinList"),
    url(r'^enquiries/create/$', enquiry.create, name="create"),
    url(r'^enquiries/code_settings/$', views.code_settings, name='code_settings'),
    url(r'^enquiries/(?P<pk>[^/]+)/delete/$', enquiry.delete, name="delete"),
    url(r'^enquiries/pending_follow_ups/$', enquiry.pending_follow_ups, name="pending_follow_ups"),
    url(r'^enquiry/(?P<pk>[^/]+)/details/$', enquiry.enquiry_detail, name="enquiry_detail"),
    url(r'^enquiry/(?P<pk>[^/]+)/edit/$', enquiry.edit, name="edit"),
    url(r'^enquiry/activity/(?P<pk>[^/]+)/complete/$', enquiry.complete_activity, name="complete_activity"),
    url(r'^registration/$', enquiry.new_registration, name="new_registration"),
    url(r'^confirm/$', enquiry.confirm_new_registration, name="confirm_new_registration"),
    url(r'^confirm/(?P<pk>[^/]+)/$', enquiry.confirm_new_registration, name="confirm_new_registration"),

    # Activity urls
    url(r'^enquiries/(?P<enquiry_pk>[^/]+)/activities/create/$', views.create_activity, name="add_activity"),
    url(r'^activity/(?P<pk>[^/]+)/edit/$', views.edit_activity, name="edit_activity"),
    url(r'^activity/(?P<pk>[^/]+)/delete/$', views.delete_activity, name="delete_activity"),
    url(r'^activity/(?P<pk>[^/]+)/view/$', views.view_activity, name="view_activity"),
    url(r'^enquiries/(?P<pk>[^/]+)/activity_type/$', views.create_activity_type, name="create_activity_type"),
    url(r'^activity/(?P<pk>[^/]+)/change_status/$', views.change_status, name="change_status"),
    url(r'^activity/(?P<pk>[^/]+)/enquiry_change_status/$', views.enquiry_change_status, name="enquiry_change_status"),
    url(r'^import/$', views.import_enquiry, name="import"),
    url(r'^followups/$', enquiry.myfollowups, name="myfollowups"),
    url(r'^enrollment/report/$', views.enrolment_report, name='enrolment_report'),
    url(r'^enrollment/daily/report/$', views.enrolment_report_daily_report, name='enrolment_report_daily_report'),

]

student/urls.py
from django.conf.urls import include, url
from student import views

app_name = "student"

urlpatterns = [
    url(r'^student/', include([
        url(r'^$', views.index, name="list"),
        url(r'^indexdetail/$', views.detail_index, name="detail_index"),
        url(r'^certificatedetail/(?P<pk>[^/]+)/$', views.certificate_detail, name="certificatedetail"),
        url(r'^studentprofile/$', views.student_profile, name="student_profile"),
        url(r'^create/(?P<pk>[^/]+)/$', views.create, name="create"),
        url(r'^edit/(?P<pk>[^/]+)/$', views.edit, name="edit"),
        url(r'^studentprofileedit/(?P<pk>[^/]+)/$', views.student_profile_edit, name="student_profile_edit"),
        url(r'^delete/(?P<pk>[^/]+)/$', views.delete, name="delete"),
        url(r'^loanstatus/(?P<pk>[^/]+)/$', views.loanstatus, name="loanstatus"),
        url(r'^detail/(?P<pk>[^/]+)/$', views.detail, name="detail"),
        url(r'^payments/(?P<pk>[^/]+)/$', views.installments, name="payments"),
        url(r'^(?P<pk>[^/]+)/pay/(?P<installment>[^/]+)/$', views.make_payment, name="make_payment"),
        url(r'^(?P<pk>[^/]+)/$', views.add_discount, name="add_discount"),
        url(r'^(?P<pk>[^/]+)/installments/$', views.student_installments, name='student_installments'),
        url(r'^(?P<studentcourse_pk>[^/]+)/payments/$', views.student_payments, name="student_payments"),
        url(r'^profile/edit(?P<pk>[^/]+)$', views.student_edit, name="student_edit"),
        url(r'^(?P<student_course_pk>[^/]+)/create_payment/$', views.create_first_installment,
            name="create_first_installment"),
        url(r'^installments/(?P<pk>[^/]+)$', views.installments, name="installments"),
        url(r'^(?P<pk>[^/]+)/pay/$', views.pay, name="pay"),
        url(r'^changestatus/(?P<pk>[^/]+)/$', views.changeStatus, name="changeStatus"),
        url(r'^(?P<pk>[^/]+)/setDiscount/$', views.setDiscount, name="setDiscount"),
        url(r'^(?P<pk>[^/]+)/addCourse/$', views.addStudentCourse, name="addStudentCourse"),
        url(r'^(?P<pk>[^/]+)/deleteCourse/$', views.deleteStudentCourse, name="deleteStudentCourse"),
        url(r'^(?P<pk>[^/]+)/editCourse/$', views.editStudentCourse, name="editStudentCourse"),
        url(r'^(?P<pk>[^/]+)/viewCourse/$', views.viewStudentCourse, name="viewStudentCourse"),
        url(r'^(?P<studentcourse_pk>[^/]+)/invoice/$', views.student_invoice, name="student_invoice"),
        url(r'^(?P<pk>[^/]+)/previewPdf/$', views.CertificatePDFView, name="certificate_pdf"),
        url(r'^(?P<pk>[^/]+)/marksheet/$', views.mark_sheet, name="marksheet"),
        url(r'^(?P<pk>[^/]+)/edit/certificate/$', views.edit_certificate, name="editcertificate"),
        url(r'^(?P<studentcourse_pk>[^/]+)/subjects/$', views.student_course_subjects, name="student_course_subjects"),
        url(r'^(?P<studentcourse_pk>[^/]+)/certificate/$', views.course_certificate, name="course_certificate"),
        url(r'^(?P<studentcourse_pk>[^/]+)/certificate/edit/$', views.course_certificate_edit, name="course_certificate_edit"),
        url(r'^(?P<studentcourse_pk>[^/]+)/extrapay/$', views.extraPay, name="extraPay"),
        url(r'^edit/(?P<student_installment_pk>[^/]+)/extrapay/$', views.edit_extraPay, name="edit_extraPay"),
        url(r'^(?P<student_pk>[^/]+)/payment_history/$', views.payment_history, name="payment_history"),
        url(r'^(?P<installment_pk>[^/]+)/installment/payment_history/$', views.installment_payment_history, name="installment_payment_history"),

    ])),
    url(r'^working_fee/$', views.working_fee, name="working_fee"),
    url(r'^working_fee/summary/$', views.summary_working_fee, name="summary_working_fee"),
    url(r'^fee/reminder/$', views.fee_reminder, name="fee_reminder"),
    url(r'^course/monthly/summary/$', views.course_monthly_summary, name="course_monthly_summary"),
    url(r'^invoice/(?P<pk>[^/]+)/detail.pdf/$', views.InvoicePDFView.as_view(), name="invoice_pdf"),
    url(r'^import/student/$', views.import_student, name="import_student"),
    url(r'^assigned_students/$', views.my_students, name="my_students"),
    url(r'^marksheet/(?P<pk>[^/]+)/edit/$', views.mark_sheet_edit, name="mark_sheet_edit"),
    # url(r'^import/student/$', views.import_installment, name="import_installment"),
    url(r'^import_pays/$', views.import_pays, name="import_pays"),
    url(r'^marksheet/(?P<pk>[^/]+)/delete/$', views.mark_sheet_delete, name="mark_sheet_delete"),
    url(r'^certificate_verification_page/$', views.certificate_verification, name="certificate_verification_page"),
    url(r'^certificate_verification/$', views.CertificateDetail.as_view({'get': 'detail'}), name="certificate_verification"),

]

student/models.py
import math
from _decimal import Decimal
from decimal import getcontext, ROUND_UP

from django.db import models
from django.db.models import Q, Sum
from django.utils import timezone
from address.models import Address, Contact
from employee.models import Employee
from erp_core.models import ErpAbstractBaseModel, BaseCodeSetting
from enquiry.models import Enquiry
from product.models import Course, CourseCertification, Subject
from django.contrib.auth.models import User


class Student(ErpAbstractBaseModel):
    SEX = (
        ('Female', 'Female'),
        ('Male', 'Male'),
    )

    # @property
    def newCode():
        return StudentCodeSetting.new_code()

    code = models.CharField(max_length=20, default=newCode, unique=True)
    photo = models.FileField(upload_to='stud/%Y/%m/%d', blank=True, null=True)
    enquiry = models.OneToOneField(Enquiry, null=True, blank=True, related_name='enquiry')
    gender = models.CharField(max_length=8, choices=SEX, blank=True, null=True)
    details_filled = models.BooleanField(default=False)
    remark = models.CharField(max_length=255, null=True, blank=True)
    highest_qualification = models.CharField(max_length=255, blank=True, null=True)
    aadharno = models.CharField(max_length=255, blank=True, null=True)
    certificate = models.FileField(upload_to='certificate/%Y/%m/%d', blank=True, null=True)
    parent_name = models.CharField(max_length=255, blank=True, null=True)
    placement = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, null=True, blank=True)
    outside_kerala = models.CharField(null=True, blank=True, max_length=25)

    def __str__(self):
        return self.enquiry.name_of_candidate

    def save(self, *args, **kwargs):
        if self.code and self.created_at is None:
            StudentCodeSetting.incrementCountIndex()

        return super(Student, self).save(*args, **kwargs)

    # def studCodeGenerator(self):
    #     location_code = self.enquiry.location
    #     # time_code = self.time
    #     start_date_code = self.start_date
    #     year = str(start_date_code)[2:4]
    #     stud_code = 'I' + str(location_code) + str(year)
    #     return stud_code


class AddressForStudent(Address):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, related_name="student_address")

    def __str__(self):
        return str(self.student)


class ContactForStudent(Contact):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, related_name="student_contact")

    def __str__(self):
        return str(self.student)


class StudentCodeSetting(BaseCodeSetting):
    pass


class StudentInstallment(ErpAbstractBaseModel):
    NOT_PAID = 'Not paid'
    PAID = 'Paid'
    PARTIALLY_PAID = 'Partially paid'
    STATUSES = (
        (NOT_PAID, "Not paid"),
        (PAID, "Paid"),
        (PARTIALLY_PAID, "Partially paid"),

    )
    student = models.ForeignKey('student.StudentCourse', related_name="installments")
    # installment = models.ForeignKey(CourseInstallment, related_name="course_installments", null=True, blank=True)
    date = models.DateField(default=timezone.now)
    due_date = models.DateField(default=timezone.now)
    paid_date = models.DateField(null=True, blank=True)
    paid_amount = models.DecimalField(max_digits=30, decimal_places=2, null=True, blank=True)
    remark = models.CharField(max_length=200, null=True, blank=True)
    amount_to_be_paid = models.DecimalField(max_digits=30, decimal_places=2, default=0.00)
    status = models.CharField(max_length=30, choices=STATUSES, default=NOT_PAID, blank=True)
    percentage = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.student)

    def balanceAmount(self):
        if self.amount_to_paid and self.paid_amount:
            return self.amount_to_paid - self.paid_amount
        elif not self.paid_amount:
            return self.amount_to_paid
        else:
            return 0


class StudentCourse(models.Model):
    STATUS_OPEN = 'Open'
    STATUS_COMPLETED = 'Completed'
    STATUS_DISCONTINUED = 'Discontinued'
    STATUS_ONGOING = 'Ongoing'
    STATUS_SEAT_BLOCKING = 'Seat Blocking'
    STATUSES = (
        (STATUS_OPEN, "Open"),
        (STATUS_COMPLETED, "Completed"),
        (STATUS_DISCONTINUED, "Discontinued"),
        (STATUS_ONGOING, "Ongoing"),
        (STATUS_SEAT_BLOCKING, "Seat Blocking"),

    )

    enrollment_code = models.CharField(max_length=20)
    course_code = models.CharField(max_length=50)
    student = models.ForeignKey(Student, related_name="my_courses")
    course = models.ForeignKey(Course, related_name='students')
    fees = models.PositiveIntegerField()
    discount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    no_of_installments = models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(max_length=30, choices=STATUSES, default=STATUS_OPEN)
    date_of_joining = models.DateField(null=True, blank=True)
    loan = models.BooleanField(default=False)
    closed_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    received_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    program_director = models.ForeignKey(Employee, null=True, related_name='students')
    date_of_completion = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.student)

    def save(self, *args, **kwargs):
        self.course_code = self.course.code
        if not self.enrollment_code:
            # self.course.batch.count = self.course.batch.count + 1
            if self.course.batch.name == 'IELTS(spoken)':
                student_count = StudentCourse.objects.filter(course__batch__name='IELTS').count() + 1
            elif (self.course.batch.name == 'BLS') or (self.course.batch.name == 'BLS/ACLS'):
                student_count = StudentCourse.objects.filter(
                    course__batch__name='BLS').count()
                student_count = student_count + StudentCourse.objects.filter(
                    course__batch__name='BLS/ACLS').count() + 1
            elif (self.course.batch.program.name == 'MEP') or (
                    self.course.batch.program.name == 'Hospital Administration & Management') or (
                    self.course.batch.program.name == 'Nursing Coaching Courses') or (
                    self.course.batch.program.name == 'Logistics And Supply Chain Management'):
                student_count = StudentCourse.objects.filter(
                    course__batch__program=self.course.batch.program).count() + 1

            elif self.course.batch.name == "Diploma In QA/QC Mechanical Engineering" or self.course.batch.name == 'QA/QC Mechanical Engg. (Asnt Only)':
                student_count = StudentCourse.objects.filter(
                    course__batch__name='Diploma In QA/QC Mechanical Engineering').count()

                student_count = student_count + StudentCourse.objects.filter(
                    course__batch__name='QA/QC Mechanical Engg. (Asnt Only)').count() + 1

            else:
                student_count = StudentCourse.objects.filter(course__batch=self.course.batch).count() + 1
            self.course.batch.count = student_count

            self.enrollment_code = "IA" + self.course.batch.enrollment_abbreviation + str(
                format(student_count, '0' + str(3) + 'd'))
            self.course.batch.save()
            self.course.save()
        self.program_director = self.course.batch.program.program_director
        return super(StudentCourse, self).save(*args, **kwargs)

    def cumulative_gpa(self):
        mark = self.subjects.aggregate(tpe=Sum('points_earned'), tmca=Sum('max_credit_awarded'))
        if mark['tpe']:
            result = mark['tpe'] / mark['tmca']
            result = Decimal(result).quantize(Decimal('.01'), rounding=ROUND_UP)
        else:
            result = 0.00
        return result

    def ceu_awarded(self):
        ceu = self.subjects.aggregate(tcha=Sum('class_attendance_hours'))
        if ceu['tcha']:
            return (ceu['tcha'] / 10)
        return (0.00)

        # def calculate_aggregate(self):
        #     total_contact_hours = 0
        #     total_class_attendance_hours = 0
        #     total_grade = 0
        #     total_max_credit_awarded = 0
        #     total_mark_received = 0
        #     totalpoints_earned = 0
        #     for subject in self.subjects.all():
        #         total_contact_hours += subject.total_contact_hours
        #         total_class_attendance_hours += subject.class_attendance_hours
        #         total_mark_received += subject.mark_received
        #         total_grade += subject.grade
        #         total_max_credit_awarded += subject.max_credit_awarded
        #         totalpoints_earned += subject.points_earned

        # self.cue_awarded = (total_class_attendance_hours / 10)
        # self.cumulative_gpa = totalpoints_earned / total_max_credit_awarded

        return self

    def contact_hours_calculate_aggregate(self):
        total_contact_hours = 0

        for subject in self.subjects.all():
            total_contact_hours += subject.total_contact_hours

        return total_contact_hours

    def mark_received_calculate_aggregate(self):
        total_mark_received = 0

        for subject in self.subjects.all():
            total_mark_received += subject.mark_received

        return total_mark_received

    def class_attendance_hours_calculate_aggregate(self):
        total_class_attendance_hours = 0

        for subject in self.subjects.all():
            total_class_attendance_hours += subject.class_attendance_hours

        return total_class_attendance_hours

    def grade_calculate_aggregate(self):
        total_grade = 0

        for subject in self.subjects.all():

student/templates/reminders/fee_remainder.html
{% extends "erp_admin/base.html" %}{% load static humanize %}

{% block head %}
<style>


@media print {

  a[href]:after {
    content: none!important;
  }
  .noprint{
    display:none!important;

  }
  }

</style>
{% endblock head %}
{% block content %}


<!-- Modal -->
<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Filters</h4>
          </div>
          <div class="modal-body">
            <form action="" method="get">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Course</label>
                            {{ filter.form.course }}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{ filter.form.name.label }}</label>
                            {{ filter.form.name }}
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </form>
          </div>
          <div class="modal-footer">

          </div>
    </div>
  </div>
</div>

<div class="content-main">
        <div class="block">
            <div class="row show-grid">
                <div class="col-sm-3">
                    <h3>
                        Students

                    </h3>
                </div>
                <div class="col-sm-9">
                    <div class="pull-right">

                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#filter-modal">
                          <i class="fa fa-filter"></i> Apply Filters
                        </button>
                        <a class="btn btn-primary  btn-sm" href="{% url 'student:fee_reminder' %}">
                            <i class="fa fa-refresh"></i> Refresh
                        </a>

                            <a onclick="printDiv()" class="btn btn-primary" target="__blank"> <i class="fa fa-print fa-fw"></i> Print Report</a>

                    </div>
                </div>
            </div>
            <div class="row show-grid">
                <div class="col-sm-12" id="print_receipt">
                    <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Course</th>
                                <th>Pending Amount</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for installment in installments %}
                                <tr class="">
                                    <td scope="row">{{ forloop.counter}}</td>
                                    <td>
                                        <a href="{% url 'student:detail' installment.student.student.pk %}">{{ installment.student}}</a>
                                    </td>
                                    <td>{{installment.student.course.name}}</td>
                                    <td>{{ installment.amount_to_be_paid }}</td>

                                </tr>
                                {% empty %}
                                <tr><td colspan="6">No Data  </td></tr>
                            {% endfor %}
                       </tbody>
                    </table>
                </div>
            </div>
                <div id="pagination">

                </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block jsscript %}
<!-- <script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script> -->
<!-- <script>
$(document).ready(function(){
     var $date_inputs = $('#id_date,#id_next_follow_up_date')
    var date_format = 'YYYY-MM-DD';
    $date_inputs.daterangepicker({
        singleDatePicker: true,
        autoUpdateInput: false,
        // timePicker: true,
        // timePicker24Hour: false,
        autoApply: true,
        showDropdowns: true,
        locale: {
            format: date_format,
        },
        // calender_style: "picker_4",
    }, function(start, end, label) {
        console.log(start.toISOString(), end.toISOString(), label);
    });


    $date_inputs.on('apply.daterangepicker', function(ev, picker) {
        $(this).val(picker.startDate.format('YYYY-MM-DD'));
    });

    $date_inputs.on('cancel.daterangepicker', function(ev, picker) {
        $(this).val('');
    });


    $('form.delete').submit( function (e){
        e.preventDefault()
        e.stopPropagation()
        if(confirm('Do you want to Delete the entire student Details')){
            this.submit()
        }
    })

    $(".fade-in").addClass("load")


});
</script> -->
<script>


    function printDiv() {
    var printContents = document.getElementById('print_receipt').innerHTML;
    var originalContents = document.body.innerHTML;
     document.body.innerHTML = printContents;
     window.print();
     document.body.innerHTML = originalContents;
    }
</script>
{% endblock jsscript %}

student/templates/reminders/follow_ups.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static %}
{% block head %}
<style type="text/css">

</style>
{% endblock head %}
{% block content %}

<!-- Modal -->
<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Filters</h4>
            </div>
            <div class="modal-body">
                <form action="" method="get">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">{{ filter.form.date.label }}</label>
                                {{ filter.form.date }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">{{ filter.form.type.label }}
                                </label>
                                {{ filter.form.type }}
                            </div>
                        </div>


                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<div class="content-main">
    <div class="block">
        <div class="row">
            <div class="col-sm-12 col-xs-12" style="padding-left:30px;">

            </div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-6">
                <h3>
                    <span style="color:#d9534f;">Follow Ups </span>

                </h3>
            </div>
            <div class="col-sm-6">
                <div class="pull-right">
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal"
                            data-target="#filter-modal">
                        <i class="fa fa-filter"></i> Filters
                    </button>
                    <a class="btn btn-primary btn-sm" href="{% url 'enquiry:myfollowups' %}">
                        <i class="fa fa-refresh"></i> Refresh
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Date</th>
                            <th>Enquiry</th>
                            <th>Enquiry Status</th>
                            <th></th>
                            <th></th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for activity in activities %}
                        <tr>
                            <td scope="row">{{ forloop.counter }}</td>
                            <td>{{activity.date}}</td>
                            <td>
                                <a href="{% url 'enquiry:enquiry_detail' activity.enquiry.pk %}">{{activity.enquiry}}</a>
                            </td>
                            <td>{{ activity.enquiry.status }}</td>
                            <td>
                            <select class="form-control statusbutton" name="status" data-value="{{activity.pk}}">
                                {% for status in statuses %}
                                <option {% if activity.status == status.1 %}selected{% endif %}><a href="" data-value="{{ activity.pk }}">{{status.1}}</a>
                                </option>
                                {% endfor %}
                            </select>
                        </td>
                            <td>
                                <a href="{% url 'enquiry:delete_activity' activity.pk %}" class="btn btn-primary btn-xs"><i
                                    class="fa fa-trash-o"></i></a>
                                <a href="{% url 'enquiry:view_activity' activity.pk %}" class="btn btn-primary btn-xs"><i
                                    class="fa fa-eye"></i></a>
                            </td>


                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="8">No Followups</td>
                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <div id="pagination">
                    {{pagination|safe}}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block jsscript %}
<script src="{% static 'js/moment.min.js' %}"></script>

<script src="{% static 'js/daterangepicker.js' %}"></script>
<script>
function getCookie(name) {
   var cookieValue = null;
   if (document.cookie && document.cookie != '') {
       var cookies = document.cookie.split(';');
       for (var i = 0; i < cookies.length; i++) {
           var cookie = jQuery.trim(cookies[i]);
           // Does this cookie string begin with the name we want?
           if (cookie.substring(0, name.length + 1) == (name + '=')) {
               cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
               break;
           }
       }
   }
   return cookieValue;
}
var csrftoken = getCookie('csrftoken');
function csrfSafeMethod(method) {
   // these HTTP methods do not require CSRF protection
   return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
   beforeSend: function(xhr, settings) {
       if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
           xhr.setRequestHeader("X-CSRFToken", csrftoken);
       }
   }
});

$(document).ready(function() {
    $('#id_date').daterangepicker({
        singleDatePicker: true,
        autoUpdateInput: false,
        showDropdowns: true,
        locale: {
            format: 'YYYY-MM-DD',
            cancelLabel: 'Clear'
        },
        }, function(start, end, label)
        {console.log(start.toISOString(), end.toISOString(), label);});
         $('#id_date').on('apply.daterangepicker', function(ev, picker) {
            $(this).val(picker.startDate.format('YYYY-MM-DD'));
          });

         $('input[name="datefilter"]').on('cancel.daterangepicker', function(ev, picker) {
                $(this).val('');
            });

    $(".statusbutton").change(function(event){
       var selectedStatus = $(this).children("option:selected").val();

       var primek = $(this).data("value")
       console.log(primek)
       if (confirm("Confirm?"))
       $(this).val(selectedStatus);
       {
           $.ajax(
           {
               url : '/activity/' + primek + '/change_status/',
               type: "POST",
               data: {
                 'status': selectedStatus
               },
               success:function(data)
               {
                   console.log('success')
               },
               error: function(jqXHR, textStatus, errorThrown)
               {
                   console.log('failed')
               }
           });
       }
     });
    });


</script>
{% endblock jsscript %}