crm/urls.py
from django.conf.urls import url
from crm import campaign

app_name = "crm"

urlpatterns = [

    url(r'^campaign/create/$', campaign.campaign_create, name="campaign_create"),
    url(r'^campaign/list/$', campaign.campaign_list, name="campaign_list"),
    url(r'^campaign/(?P<pk>[^/]+)/detail/$', campaign.campaign_detail, name="campaign_detail"),
    url(r'^campaign/(?P<pk>[^/]+)/edit/$', campaign.campaign_edit, name="campaign_edit"),
    url(r'^campaign/(?P<pk>[^/]+)/list_products/$', campaign.products, name="products"),


]

student/urls.py
from django.conf.urls import include, url
from student import views

app_name = "student"

urlpatterns = [
    url(r'^student/', include([
        url(r'^$', views.index, name="list"),
        url(r'^indexdetail/$', views.detail_index, name="detail_index"),
        url(r'^certificatedetail/(?P<pk>[^/]+)/$', views.certificate_detail, name="certificatedetail"),
        url(r'^studentprofile/$', views.student_profile, name="student_profile"),
        url(r'^create/(?P<pk>[^/]+)/$', views.create, name="create"),
        url(r'^edit/(?P<pk>[^/]+)/$', views.edit, name="edit"),
        url(r'^studentprofileedit/(?P<pk>[^/]+)/$', views.student_profile_edit, name="student_profile_edit"),
        url(r'^delete/(?P<pk>[^/]+)/$', views.delete, name="delete"),
        url(r'^loanstatus/(?P<pk>[^/]+)/$', views.loanstatus, name="loanstatus"),
        url(r'^detail/(?P<pk>[^/]+)/$', views.detail, name="detail"),
        url(r'^payments/(?P<pk>[^/]+)/$', views.installments, name="payments"),
        url(r'^(?P<pk>[^/]+)/pay/(?P<installment>[^/]+)/$', views.make_payment, name="make_payment"),
        url(r'^(?P<pk>[^/]+)/$', views.add_discount, name="add_discount"),
        url(r'^(?P<pk>[^/]+)/installments/$', views.student_installments, name='student_installments'),
        url(r'^(?P<studentcourse_pk>[^/]+)/payments/$', views.student_payments, name="student_payments"),
        url(r'^profile/edit(?P<pk>[^/]+)$', views.student_edit, name="student_edit"),
        url(r'^(?P<student_course_pk>[^/]+)/create_payment/$', views.create_first_installment,
            name="create_first_installment"),
        url(r'^installments/(?P<pk>[^/]+)$', views.installments, name="installments"),
        url(r'^(?P<pk>[^/]+)/pay/$', views.pay, name="pay"),
        url(r'^changestatus/(?P<pk>[^/]+)/$', views.changeStatus, name="changeStatus"),
        url(r'^(?P<pk>[^/]+)/setDiscount/$', views.setDiscount, name="setDiscount"),
        url(r'^(?P<pk>[^/]+)/addCourse/$', views.addStudentCourse, name="addStudentCourse"),
        url(r'^(?P<pk>[^/]+)/deleteCourse/$', views.deleteStudentCourse, name="deleteStudentCourse"),
        url(r'^(?P<pk>[^/]+)/editCourse/$', views.editStudentCourse, name="editStudentCourse"),
        url(r'^(?P<pk>[^/]+)/viewCourse/$', views.viewStudentCourse, name="viewStudentCourse"),
        url(r'^(?P<studentcourse_pk>[^/]+)/invoice/$', views.student_invoice, name="student_invoice"),
        url(r'^(?P<pk>[^/]+)/previewPdf/$', views.CertificatePDFView, name="certificate_pdf"),
        url(r'^(?P<pk>[^/]+)/marksheet/$', views.mark_sheet, name="marksheet"),
        url(r'^(?P<pk>[^/]+)/edit/certificate/$', views.edit_certificate, name="editcertificate"),
        url(r'^(?P<studentcourse_pk>[^/]+)/subjects/$', views.student_course_subjects, name="student_course_subjects"),
        url(r'^(?P<studentcourse_pk>[^/]+)/certificate/$', views.course_certificate, name="course_certificate"),
        url(r'^(?P<studentcourse_pk>[^/]+)/certificate/edit/$', views.course_certificate_edit, name="course_certificate_edit"),
        url(r'^(?P<studentcourse_pk>[^/]+)/extrapay/$', views.extraPay, name="extraPay"),
        url(r'^edit/(?P<student_installment_pk>[^/]+)/extrapay/$', views.edit_extraPay, name="edit_extraPay"),
        url(r'^(?P<student_pk>[^/]+)/payment_history/$', views.payment_history, name="payment_history"),
        url(r'^(?P<installment_pk>[^/]+)/installment/payment_history/$', views.installment_payment_history, name="installment_payment_history"),

    ])),
    url(r'^working_fee/$', views.working_fee, name="working_fee"),
    url(r'^working_fee/summary/$', views.summary_working_fee, name="summary_working_fee"),
    url(r'^fee/reminder/$', views.fee_reminder, name="fee_reminder"),
    url(r'^course/monthly/summary/$', views.course_monthly_summary, name="course_monthly_summary"),
    url(r'^invoice/(?P<pk>[^/]+)/detail.pdf/$', views.InvoicePDFView.as_view(), name="invoice_pdf"),
    url(r'^import/student/$', views.import_student, name="import_student"),
    url(r'^assigned_students/$', views.my_students, name="my_students"),
    url(r'^marksheet/(?P<pk>[^/]+)/edit/$', views.mark_sheet_edit, name="mark_sheet_edit"),
    # url(r'^import/student/$', views.import_installment, name="import_installment"),
    url(r'^import_pays/$', views.import_pays, name="import_pays"),
    url(r'^marksheet/(?P<pk>[^/]+)/delete/$', views.mark_sheet_delete, name="mark_sheet_delete"),
    url(r'^certificate_verification_page/$', views.certificate_verification, name="certificate_verification_page"),
    url(r'^certificate_verification/$', views.CertificateDetail.as_view({'get': 'detail'}), name="certificate_verification"),

]

crm/models.py
from django.db import models
from erp_core.models import ErpAbstractBaseModel
from django.core.validators import MinValueValidator
from location.models import City


class Media(ErpAbstractBaseModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class CampaignCategory(ErpAbstractBaseModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Campaign(ErpAbstractBaseModel):
    ONLINE = 'online'
    OFFLINE = 'offline'
    TYPES = (
        (ONLINE, "online"),
        (OFFLINE, "offline"),
    )
    name = models.CharField(max_length=255)
    media_type = models.CharField(max_length=30, choices=TYPES,default=TYPES[0])
    budget = models.DecimalField(max_digits=20, decimal_places=2, default=0, validators=[MinValueValidator(0)])
    description = models.TextField()
    offer_details = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    no_of_responses = models.PositiveIntegerField(default=0)
    no_of_conversions = models.PositiveIntegerField(default=0)
    group = models.TextField('Campaign Group', null=True, blank=True)

    media = models.ForeignKey(Media, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(CampaignCategory, on_delete=models.CASCADE)
    location = models.ForeignKey(City, on_delete=models.CASCADE, null=True, blank=True)



    def __str__(self):
        return self.name

student/models.py
import math
from _decimal import Decimal
from decimal import getcontext, ROUND_UP

from django.db import models
from django.db.models import Q, Sum
from django.utils import timezone
from address.models import Address, Contact
from employee.models import Employee
from erp_core.models import ErpAbstractBaseModel, BaseCodeSetting
from enquiry.models import Enquiry
from product.models import Course, CourseCertification, Subject
from django.contrib.auth.models import User


class Student(ErpAbstractBaseModel):
    SEX = (
        ('Female', 'Female'),
        ('Male', 'Male'),
    )

    # @property
    def newCode():
        return StudentCodeSetting.new_code()

    code = models.CharField(max_length=20, default=newCode, unique=True)
    photo = models.FileField(upload_to='stud/%Y/%m/%d', blank=True, null=True)
    enquiry = models.OneToOneField(Enquiry, null=True, blank=True, related_name='enquiry')
    gender = models.CharField(max_length=8, choices=SEX, blank=True, null=True)
    details_filled = models.BooleanField(default=False)
    remark = models.CharField(max_length=255, null=True, blank=True)
    highest_qualification = models.CharField(max_length=255, blank=True, null=True)
    aadharno = models.CharField(max_length=255, blank=True, null=True)
    certificate = models.FileField(upload_to='certificate/%Y/%m/%d', blank=True, null=True)
    parent_name = models.CharField(max_length=255, blank=True, null=True)
    placement = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, null=True, blank=True)
    outside_kerala = models.CharField(null=True, blank=True, max_length=25)

    def __str__(self):
        return self.enquiry.name_of_candidate

    def save(self, *args, **kwargs):
        if self.code and self.created_at is None:
            StudentCodeSetting.incrementCountIndex()

        return super(Student, self).save(*args, **kwargs)

    # def studCodeGenerator(self):
    #     location_code = self.enquiry.location
    #     # time_code = self.time
    #     start_date_code = self.start_date
    #     year = str(start_date_code)[2:4]
    #     stud_code = 'I' + str(location_code) + str(year)
    #     return stud_code


class AddressForStudent(Address):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, related_name="student_address")

    def __str__(self):
        return str(self.student)


class ContactForStudent(Contact):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, related_name="student_contact")

    def __str__(self):
        return str(self.student)


class StudentCodeSetting(BaseCodeSetting):
    pass


class StudentInstallment(ErpAbstractBaseModel):
    NOT_PAID = 'Not paid'
    PAID = 'Paid'
    PARTIALLY_PAID = 'Partially paid'
    STATUSES = (
        (NOT_PAID, "Not paid"),
        (PAID, "Paid"),
        (PARTIALLY_PAID, "Partially paid"),

    )
    student = models.ForeignKey('student.StudentCourse', related_name="installments")
    # installment = models.ForeignKey(CourseInstallment, related_name="course_installments", null=True, blank=True)
    date = models.DateField(default=timezone.now)
    due_date = models.DateField(default=timezone.now)
    paid_date = models.DateField(null=True, blank=True)
    paid_amount = models.DecimalField(max_digits=30, decimal_places=2, null=True, blank=True)
    remark = models.CharField(max_length=200, null=True, blank=True)
    amount_to_be_paid = models.DecimalField(max_digits=30, decimal_places=2, default=0.00)
    status = models.CharField(max_length=30, choices=STATUSES, default=NOT_PAID, blank=True)
    percentage = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.student)

    def balanceAmount(self):
        if self.amount_to_paid and self.paid_amount:
            return self.amount_to_paid - self.paid_amount
        elif not self.paid_amount:
            return self.amount_to_paid
        else:
            return 0


class StudentCourse(models.Model):
    STATUS_OPEN = 'Open'
    STATUS_COMPLETED = 'Completed'
    STATUS_DISCONTINUED = 'Discontinued'
    STATUS_ONGOING = 'Ongoing'
    STATUS_SEAT_BLOCKING = 'Seat Blocking'
    STATUSES = (
        (STATUS_OPEN, "Open"),
        (STATUS_COMPLETED, "Completed"),
        (STATUS_DISCONTINUED, "Discontinued"),
        (STATUS_ONGOING, "Ongoing"),
        (STATUS_SEAT_BLOCKING, "Seat Blocking"),

    )

    enrollment_code = models.CharField(max_length=20)
    course_code = models.CharField(max_length=50)
    student = models.ForeignKey(Student, related_name="my_courses")
    course = models.ForeignKey(Course, related_name='students')
    fees = models.PositiveIntegerField()
    discount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    no_of_installments = models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(max_length=30, choices=STATUSES, default=STATUS_OPEN)
    date_of_joining = models.DateField(null=True, blank=True)
    loan = models.BooleanField(default=False)
    closed_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    received_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    program_director = models.ForeignKey(Employee, null=True, related_name='students')
    date_of_completion = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.student)

    def save(self, *args, **kwargs):
        self.course_code = self.course.code
        if not self.enrollment_code:
            # self.course.batch.count = self.course.batch.count + 1
            if self.course.batch.name == 'IELTS(spoken)':
                student_count = StudentCourse.objects.filter(course__batch__name='IELTS').count() + 1
            elif (self.course.batch.name == 'BLS') or (self.course.batch.name == 'BLS/ACLS'):
                student_count = StudentCourse.objects.filter(
                    course__batch__name='BLS').count()
                student_count = student_count + StudentCourse.objects.filter(
                    course__batch__name='BLS/ACLS').count() + 1
            elif (self.course.batch.program.name == 'MEP') or (
                    self.course.batch.program.name == 'Hospital Administration & Management') or (
                    self.course.batch.program.name == 'Nursing Coaching Courses') or (
                    self.course.batch.program.name == 'Logistics And Supply Chain Management'):
                student_count = StudentCourse.objects.filter(
                    course__batch__program=self.course.batch.program).count() + 1

            elif self.course.batch.name == "Diploma In QA/QC Mechanical Engineering" or self.course.batch.name == 'QA/QC Mechanical Engg. (Asnt Only)':
                student_count = StudentCourse.objects.filter(
                    course__batch__name='Diploma In QA/QC Mechanical Engineering').count()

                student_count = student_count + StudentCourse.objects.filter(
                    course__batch__name='QA/QC Mechanical Engg. (Asnt Only)').count() + 1

            else:
                student_count = StudentCourse.objects.filter(course__batch=self.course.batch).count() + 1
            self.course.batch.count = student_count

            self.enrollment_code = "IA" + self.course.batch.enrollment_abbreviation + str(
                format(student_count, '0' + str(3) + 'd'))
            self.course.batch.save()
            self.course.save()
        self.program_director = self.course.batch.program.program_director
        return super(StudentCourse, self).save(*args, **kwargs)

    def cumulative_gpa(self):
        mark = self.subjects.aggregate(tpe=Sum('points_earned'), tmca=Sum('max_credit_awarded'))
        if mark['tpe']:
            result = mark['tpe'] / mark['tmca']
            result = Decimal(result).quantize(Decimal('.01'), rounding=ROUND_UP)
        else:
            result = 0.00
        return result

    def ceu_awarded(self):
        ceu = self.subjects.aggregate(tcha=Sum('class_attendance_hours'))
        if ceu['tcha']:
            return (ceu['tcha'] / 10)
        return (0.00)

        # def calculate_aggregate(self):
        #     total_contact_hours = 0
        #     total_class_attendance_hours = 0
        #     total_grade = 0
        #     total_max_credit_awarded = 0
        #     total_mark_received = 0
        #     totalpoints_earned = 0
        #     for subject in self.subjects.all():
        #         total_contact_hours += subject.total_contact_hours
        #         total_class_attendance_hours += subject.class_attendance_hours
        #         total_mark_received += subject.mark_received
        #         total_grade += subject.grade
        #         total_max_credit_awarded += subject.max_credit_awarded
        #         totalpoints_earned += subject.points_earned

        # self.cue_awarded = (total_class_attendance_hours / 10)
        # self.cumulative_gpa = totalpoints_earned / total_max_credit_awarded

        return self

    def contact_hours_calculate_aggregate(self):
        total_contact_hours = 0

        for subject in self.subjects.all():
            total_contact_hours += subject.total_contact_hours

        return total_contact_hours

    def mark_received_calculate_aggregate(self):
        total_mark_received = 0

        for subject in self.subjects.all():
            total_mark_received += subject.mark_received

        return total_mark_received

    def class_attendance_hours_calculate_aggregate(self):
        total_class_attendance_hours = 0

        for subject in self.subjects.all():
            total_class_attendance_hours += subject.class_attendance_hours

        return total_class_attendance_hours

    def grade_calculate_aggregate(self):
        total_grade = 0

        for subject in self.subjects.all():

student/templates/student/course_monthly_summary.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static %}
{% block head %}
<style type="text/css">
.tbl
{
    color:#000000;
    font-size:14px;

}

</style>
{% endblock head %}
{% block content %}
<div class="banner">
    <div class="row">
        <div class="col-sm-12">

            <form id="form" action="" method="get">
                {% csrf_token %}

                <div class="col-sm-2">
                    <label>Select Date </label>
                </div>
                <div class="col-sm-3">
                    <input type="text" name="month_year" class="form-control tdate" value="">
                </div>
                <div class="col-sm-1">
                    <button type="submit" name="search" class="btn btn-primary"><i class="fa fa-search"></i>
                    </button>
                </div>
                <div class="col-sm-1">
                    <a href="{% url 'student:course_monthly_summary' %}" name="search" class="btn btn-primary"> <i
                            class="fa fa-refresh"></i></a>
                </div>
                <div class="col-sm-1">
                    <a onclick="printDiv()" class="btn btn-primary" target="__blank"> <i
                            class="fa fa-print fa-fw"></i> Print Report</a>
                </div>
            </form>
        </div>

    </div>

</div>
<div class="blank">
    <div class="blank-page">
        <div class="row show-grid">
            <h3> Course Summary Report: {{start|date:"d M Y"}}{% if start != end %}- {{end|date:"d M Y"}}{% endif %}</h3>

            <div class="col-md-12 table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <th>Course</th>
                    <th>Total Students</th>

                    </thead>
                    <tbody>
                    {% for course in courses %}
                    <tr>
                        <td>{{ course.name }}</td>
                        <td>{{ course.total_students }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="2">No Data</td>
                    </tr>
                    {% endfor %}
                    </tbody>

                </table>

            </div>

        </div>
    </div>
</div>


{% endblock content %}
{% block jsscript %}

<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>

<script>
$(function() {
  $('input[name="month_year"]').daterangepicker({
    opens: 'left',
    autoUpdateInput:false,
    locale: {
        format: 'YYYY-MM-DD',
      },
  },

);
});

    $('.tdate').on('apply.daterangepicker', function(ev, picker) {
        var dd = picker.startDate.format('YYYY-MM-DD')+"-"+picker.endDate.format('YYYY-MM-DD');
        $(this).val(dd);
    });

    $('.tdate').on('cancel.daterangepicker', function(ev, picker) {
        $(this).val('');
    });



    function printDiv() {
    var printContents = document.getElementById('print_receipt').innerHTML;
    var originalContents = document.body.innerHTML;
     document.body.innerHTML = printContents;
     window.print();
     document.body.innerHTML = originalContents;
    }









</script>

{% endblock jsscript %}

student/templates/student/email.html
<html>
<body>
<p>Hi {{invoice.student}}</p>

<p>We hope you’re doing well. Your payment of Rs
        {{current_amount}}  is received on
        {{date}} </p><p>With Regards ,</p><p>IBIS Groups</p>"
<!--<img src="/media/{{invoice.img}}" width="130px" height="130px">-->

</body>
</html>

student/templates/student/index.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static group_required util %}
{% block head %}
<style>
.status-open {
    background-color: #2fd22f;
    font-size: 16px;
}
.status-rejected {
    background-color: red;
    font-size: 12px;
}
.fade-in {
    opacity: 0;
    font-size: 21px;
    margin-top: 25px;
    text-align: center;

    -webkit-transition: opacity .3s ease-in;
       -moz-transition: opacity .3s ease-in;
        -ms-transition: opacity .3s ease-in;
         -o-transition: opacity .3s ease-in;
            transition: opacity .3s ease-in;
}

.fade-in.load {
    opacity: 1;
}
.fabutton {
  background: none;
  padding: 0px;
  border: none;
}
.table>thead>tr>th{
    color: #00ABE7!important;
    font-size: 15px!important;
    
}
@media print {

  a[href]:after {
    content: none!important;
  }
  .noprint{
    display:none!important;

  }
  }


</style>
{% endblock head %}
{% block content %}


<!-- Modal -->
<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Filters</h4>
            </div>
            <div class="modal-body">
                <form action="" method="get">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">{{ filter.form.code.label }}</label>
                                {{ filter.form.code }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">{{ filter.form.name.label }}</label>
                                {{ filter.form.name }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">Program</label>
                                {{ filter.form.program }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">Course</label>
                                {{ filter.form.course }}
                            </div>
                        </div>

                    </div>
                    <div class="row">

                        <div class="col-sm-6">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<div class="content-main">
    <div class="block">
        <div class="row show-grid">
            {% if request.user.employee.primary_designation.name == 'Ibis Admin' %}
            <div class="col-sm-12">
                {% if upload_form.errors %}
                <p style="color: red;">
                    Please correct the error{{ upload_form.errors|pluralize }} below.
                </p>
                {% else %}
                <form action="{% url 'student:import_student' %}" enctype="multipart/form-data" method="post">
                    <table>
                        {{ upload_form.as_table }}
                    </table>
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success btn-md"><i class="fa fa-upload"></i>Upload Excel
                    </button>
                </form>
                {% endif %}
            </div>
            {% endif %}
            <div class="col-sm-3">
                <h3>
                    Students
                </h3>
            </div>
            <div class="col-sm-9">
                <div class="pull-right">

                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal"
                            data-target="#filter-modal">
                        <i class="fa fa-filter"></i> Apply Filters
                    </button>
                    <a class="btn btn-primary  btn-sm" href="{% url 'student:list' %}">
                        <i class="fa fa-refresh"></i> Refresh
                    </a>
                    {% if request.user.employee.primary_designation.name == 'Ibis Admin' %}
                    <a target="_blank" class="btn btn-primary  btn-sm" href="{% url 'student:detail_index' %}">
                        <i class="fa fa-external-link"></i> More Details
                    </a>
                    {% endif %}

                    <!--<a onclick="printDiv()" class="btn btn-primary" target="__blank"> <i class="fa fa-print fa-fw"></i>-->
                        <!--Print Report</a>-->

                </div>
            </div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-12" id="print_receipt">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Code</th>
                            <th>Name</th>
                            {% if perms.student.change_student %}

                            <th class="noprint">Edit</th>
                            {% endif %}

                            {% if perms.student.delete_student %}

                            <th class="noprint">Delete</th>
                            {% endif %}

                        </tr>
                        </thead>
                        <tbody>
                        {% for student in students %}
                        <tr>
                            <td>{% pag_count forloop.counter current_page per_page %}</td>
                            <td scope="row">{{ student.code }}</td>
                            <td>
                                <a href="{% url 'student:detail' student.pk %}">{{ student}}</a>
                            </td>

                            {% if perms.student.change_student %}
                            <td class="noprint">
                                <a href="{% url 'student:edit' student.pk %}" class=""><i class="fa fa-pencil"></i></a>
                            </td>
                            {% endif %}
                            {% if perms.student.delete_student %}

                            <td class="noprint">
                                <form class="delete" method="post" action="{% url 'student:delete' student.pk %}">{% csrf_token %}
                                    <button type="submit" class="fabutton">
                                        <i class="fa fa-trash-o fa-fw"></i>
                                    </button>
                                </form>
                            </td>
                            {% endif %}
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="6">No Data</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div id="pagination">
                {{pagination|safe}}
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block jsscript %}

<script>
     $('form.delete').submit( function (e){
        e.preventDefault()
        e.stopPropagation()
        if(confirm('Do you want to Delete the entire student Details')){
            this.submit()
        }
    })

$(document).ready(function(){
      $("#pagination a").click(function(e){
        e.preventDefault()
        page_string = this.href.slice(this.href.indexOf("?") + 1)
        var query_string = ""
        var search_query = window.location.search
        var query_obj = {}
        if(search_query){
            if(search_query.indexOf('?') > -1)
                search_query = search_query.substr(1)

            var searchQueryStrings = [search_query]
            if(search_query.indexOf('&') > -1)
                searchQueryStrings = search_query.split('&')
            searchQueryStrings.forEach(qs => {
                var query_array = qs.split('=')
                query_obj[query_array[0]] = query_array[1]
            })
        }
        query_obj['page'] = page_string.split('=')[1]
        for(var k in query_obj){
            query_string += k + '=' + query_obj[k] + '&'
        }

        // console.log(query_string, query_obj, window.location)
        window.location = window.location.pathname + "?" + query_string.slice(0, -1)
    })
});
</script>
{% endblock jsscript %}