crm/urls.py
from django.conf.urls import url
from crm import campaign

app_name = "crm"

urlpatterns = [

    url(r'^campaign/create/$', campaign.campaign_create, name="campaign_create"),
    url(r'^campaign/list/$', campaign.campaign_list, name="campaign_list"),
    url(r'^campaign/(?P<pk>[^/]+)/detail/$', campaign.campaign_detail, name="campaign_detail"),
    url(r'^campaign/(?P<pk>[^/]+)/edit/$', campaign.campaign_edit, name="campaign_edit"),
    url(r'^campaign/(?P<pk>[^/]+)/list_products/$', campaign.products, name="products"),


]

product/urls.py
from django.conf.urls import url
from product import views

app_name = "product"


urlpatterns = [
    url(r'^programs/add/$', views.add_products, name='add_products'),
    url(r'^course/(?P<course_pk>[^/]+)/edit/$',
        views.edit_course, name='edit_course'),
    url(r'^programs/$', views.view_products, name='view_products'),
    url(r'^course/(?P<pk>[^/]+)/$', views.course_detail, name='course_detail'),
    url(r'^program/(?P<pk>[^/]+)/$', views.detail, name='detail'),
    url(r'^programs/edit_program/(?P<product_pk>[^/]+)/$',
        views.edit_product, name='edit_product'),
    url(r'^programs/edit_subject/(?P<subject_pk>[^/]+)/$',
        views.edit_subject, name='edit_subject'),
    url(r'^programs/code/settings/$', views.code_settings, name='code_settings'),
    url(r'^programs/(?P<pk>[^/]+)/delete/$', views.program_delete, name='delete'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^program/(?P<pk>[^/]+)/add/course/$', views.add_course, name='add_course'),
    url(r'^subject/(?P<pk>[^/]+)/$', views.add_subject, name='add_subject'),
    url(r'^course/(?P<pk>[^/]+)/delete/$', views.delete_course, name='delete_course'),
    url(r'^programs/(?P<pk>[^/]+)/subject/delete/$', views.delete_subject, name='delete_subject'),
    url(r'^course/(?P<pk>[^/]+)/installments/$', views.add_installments, name='add_installments'),
    url(r'^source_summary_report/$', views.source_summary_report, name='source_summary_report'),
    url(r'^course/(?P<pk>[^/]+)/add/batch/$', views.add_batch, name='add_batch'),
    url(r'^batch/(?P<pk>[^/]+)/edit/$', views.edit_batch, name='edit_batch'),
    url(r'^batch/(?P<pk>[^/]+)/delete/$', views.delete_batch, name='delete_batch'),
    url(r'^course/(?P<pk>[^/]+)/certificate/add/$', views.add_certification, name='add_certification'),
    url(r'^certificate/(?P<pk>[^/]+)/edit/$', views.edit_certification, name='edit_certification'),
    url(r'^certificate/(?P<pk>[^/]+)/delete/$', views.delete_certification, name='delete_certification'),
    url(r'^course/(?P<pk>[^/]+)/subjects/$', views.add_subjects, name='add_subjects'),


]

product/models.py
import base64

import requests
from django.db import models
from django.db.models import Sum

from employee.models import Employee
from erp_core.models import BaseCodeSetting
from erp_core.models import ErpAbstractBaseModel


class Product(ErpAbstractBaseModel):
    name = models.CharField(max_length=255)
    accademic_eligibility = models.CharField(max_length=255, null=True, blank=True)
    no_of_certification = models.IntegerField(null=True, blank=True)
    certification_details = models.TextField(null=True, blank=True)
    placement_details = models.TextField(null=True, blank=True)
    abbreviation = models.CharField(max_length=10, null=True, blank=True)
    program_director = models.OneToOneField(Employee, null=True, related_name='program')

    def __str__(self):
        return self.name


class Course(ErpAbstractBaseModel):
    TWO_MONTH = '2M'
    THREE_MONTH = '3M'
    SIX_MONTH = '6M'
    TWELVE_MONTH = '12M'
    TWENTY_FOUR_DAYS = '24D'
    FOUR_DAYS = '4D'
    TWENTY_DAYS = '20D'
    TWO_DAYS = '2D'

    DURATIONS = (
        (TWO_MONTH, "2 Months"),
        (THREE_MONTH, "3 Months"),
        (SIX_MONTH, "6 Months"),
        (TWELVE_MONTH, "12 Months"),
        (TWENTY_FOUR_DAYS, "24 Days"),
        (FOUR_DAYS, "4 Days"),
        (TWENTY_DAYS, "20 Days"),
        (TWO_DAYS, "2 Days"),

    )

    NINE_ELEVEN = '9'
    NINE_ONE = 'M'
    ELEVEN_ONE = '11'
    ONE_THIRTY_THREE_THIRTY = '1.30'
    THREE_THIRTY_FIVE_THIRTY = '3.30'
    ONE_THIRTY_FIVE_THIRTY = 'A'
    TIMES = (
        (NINE_ELEVEN, "9 AM to 11AM"),
        (ELEVEN_ONE, "11 AM to 1PM"),
        (ONE_THIRTY_THREE_THIRTY, "1.30PM to 3.30PM"),
        (THREE_THIRTY_FIVE_THIRTY, "3.30PM to 5.30PM"),
        (NINE_ONE, "9 AM to 1PM"),
        (ONE_THIRTY_FIVE_THIRTY, "1.30PM to 5.30PM"),
    )

    code = models.CharField(max_length=100)
    batch = models.ForeignKey('product.Batch', related_name="batches")
    duration = models.CharField(max_length=40, choices=DURATIONS)
    time = models.CharField(max_length=40, choices=TIMES)
    start_date = models.DateField()
    total_fee = models.DecimalField("Course Fee (INR)", max_digits=20, decimal_places=2)
    course_fee = models.DecimalField("Course Fee (USD)", max_digits=20, decimal_places=2, null=True, blank=True)
    count = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.code == '' or self.code == None:
            self.code = Course.codeGenerator(self)
        return super(Course, self).save(*args, **kwargs)

    def codeGenerator(self):
        course_code = self.batch.abbreviation + '-' + self.duration + '-' + self.time + '-'+self.start_date.strftime('%d%m%y')
        return course_code

    def __str__(self):
        return self.batch.name + '(' + self.code + ')-' + str(self.start_date)

    class Meta:
        verbose_name = "Batch"
        verbose_name_plural = "Batches"
        ordering = ["-start_date",]


class Subject(ErpAbstractBaseModel):
    name = models.CharField(max_length=40)
    program = models.ForeignKey(Course, related_name='subjects', null=True)

    def __str__(self):
        return str(self.name)


class CodeSetting(BaseCodeSetting):
    pass


class CourseInstallment(ErpAbstractBaseModel):
    percentage = models.PositiveIntegerField()
    no_of_days = models.PositiveIntegerField()
    title = models.CharField(max_length=100)
    course = models.ForeignKey(Course, related_name="installments")

    def __str__(self):
        return self.course.batch.name


class Batch(ErpAbstractBaseModel):
    name = models.CharField(max_length=100)
    program = models.ForeignKey(Product, related_name="courses")
    count = models.PositiveIntegerField(default=0)
    abbreviation = models.CharField(max_length=10, null=True)
    enrollment_abbreviation = models.CharField(max_length=20, null=True)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Course"
        verbose_name_plural = "Courses"


class CourseCertification(ErpAbstractBaseModel):
    name = models.CharField(max_length=100)
    test_name = models.CharField(max_length=100)
    header_image = models.ImageField(upload_to='course_certificate/%Y/%m/%d')
    course = models.ForeignKey(Batch, related_name='certifications')

    def __str__(self):
        return self.test_name

    def get_image_as64(self):
        return base64.b64encode(requests.get('http://127.0.0.1:8000' + self.header_image.url).content)

product/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Count, Sum
from django.http import HttpResponseRedirect

from crm.models import Campaign
from easyLink.decorators import group_required
from .forms import *
from django.shortcuts import get_object_or_404, render
from .filters import ProductFilter, SubjectFilter
from django.forms import inlineformset_factory
from product.models import *
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from student.models import StudentCourse, StudentCertificate


@login_required
@group_required('front office admin')
def add_products(request):
    form = ProductsForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            messages.add_message(request, messages.INFO, 'Program created successfully')
            return HttpResponseRedirect(reverse('product:detail', args=[product.id]))
    context = {
        "form": form,
        "type": "add",
    }
    return render(request, 'product/add_products.html', context)


@login_required
def view_products(request):
    page_number = request.GET.get('page', 1)
    if request.user.employee.primary_designation.name == 'Programme Director':
        queryset = Product.objects.filter(program_director=request.user.employee)
    else:
        queryset = Product.objects.all()
    f = ProductFilter(request.GET, queryset=queryset.order_by("-created_at"))
    paginator = Paginator(f.qs, 20)

    try:
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    context = {
        "products": products,
        'filter': f,

    }
    return render(request, 'product/view_products.html', context)


@login_required
def detail(request, pk):
    product = Product.objects.get(id=pk)
    f = SubjectFilter(request.GET, queryset=Subject.objects.all().order_by("-created_at"))
    course_form = CourseForm()
    subject_form = SubjectForm()
    context = {
        "product": product,
        "pk": pk,
        "course_form": course_form,
        "subject_form": subject_form,
        "filter": f
    }
    return render(request, "product/detail.html", context)


@login_required
def edit_product(request, product_pk):
    product = Product.objects.get(id=product_pk)
    form = ProductsForm(request.POST or None, instance=product)

    if request.method == "POST":
        if form.is_valid():
            product = form.save(commit=False)
            # if 'total_fee' in form.changed_data:
            #     product.calculateGST()
            product.save()

            return HttpResponseRedirect(reverse('product:detail', args=[product.id]))
    context = {
        "form": form,
        "type": "edit",
    }
    return render(request, 'product/add_products.html', context)


@login_required
def code_settings(request):
    if CodeSetting.objects.exists():
        code_form = CodeSettingsForm(request.POST or None, instance=CodeSetting.objects.last())
    else:
        code_form = CodeSettingsForm(request.POST or None)

    if request.method == "POST":
        if code_form.is_valid():
            code_form.save()
            return HttpResponseRedirect(reverse('product:view_products'))

    context = {
        'code_form': code_form,
    }

    return render(request, "product/code_setting.html", context)


@login_required
@group_required('front office admin')
def program_delete(request, pk):
    if request.method == 'POST':
        if StudentCourse.objects.filter(course__batch__program__pk=pk).count():
            messages.add_message(request, messages.INFO,
                                 'You cannot delete the programme because you have students enrolled for this.')
        else:
            product = get_object_or_404(Product, pk=pk)
            product.delete()
    return HttpResponseRedirect(reverse('product:view_products'))


@login_required
def dashboard(request):
    return render(request, "product/dashboard.html")


@login_required
def add_course(request, pk):
    program = get_object_or_404(Product, pk=pk)
    course_form = CourseForm(request.POST)
    if course_form.is_valid():
        course = course_form.save(commit=False)
        course.program = program
        course.save()
    return HttpResponseRedirect(reverse('product:detail', args=[pk]))


@login_required
def add_subject(request, pk):
    product = get_object_or_404(Product, pk=pk)
    subject_form = SubjectForm(request.POST)
    if subject_form.is_valid():
        subject = subject_form.save(commit=False)
        subject.program = product
        subject.save()
    return HttpResponseRedirect(reverse('product:detail', args=[pk]))


@login_required
def edit_course(request, course_pk):
    course = Batch.objects.get(id=course_pk)
    form = CourseForm(request.POST or None, instance=course)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            # for batch in course.batches.all():
            #     batch.code = course.abbreviation + '-' + batch.duration + '-' + batch.time + '-'+batch.start_date.strftime('%d%m%y')
            #     batch.save()

            return HttpResponseRedirect(reverse('product:detail', args=[course.program.id]))
    context = {
        "form": form,
        "type": "edit",
        "course":course
    }
    return render(request, 'product/edit_courses.html', context)


@login_required
@group_required('front office admin')
def delete_course(request, pk):
    course = get_object_or_404(Batch, pk=pk)
    if request.method == 'POST':
        if StudentCourse.objects.filter(course__batch__pk=pk).count():
            messages.add_message(request, messages.INFO,
                                 'You cannot delete this course because you have students enrolled for this.')
        else:
            course.delete()
    return HttpResponseRedirect(reverse('product:detail', args=[course.program.id]))


@login_required
def edit_subject(request, subject_pk):
    subject = Subject.objects.get(id=subject_pk)
    form = SubjectForm(request.POST or None, instance=subject)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product:detail', args=[subject.program.id]))
    context = {
        "form": form,
        "type": "edit",
    }
    return render(request, 'product/edit_subject.html', context)


@login_required
@group_required('front office admin')
def delete_subject(request, pk):
    if request.method == 'POST':
        subject = get_object_or_404(Subject, pk=pk)
        subject.delete()
    return HttpResponseRedirect(reverse('product:detail', args=[subject.program.id]))


@login_required
@group_required('front office admin')
def add_installments(request, pk):
    course = get_object_or_404(Course, pk=pk)
    InstallmentFormSet = inlineformset_factory(Course, CourseInstallment, form=CourseInstallmentForm, extra=0,
                                               min_num=1, can_delete=True)
    installment_formset = InstallmentFormSet(instance=course)
    if request.method == "POST":
        # total = 0
        installment_formset = InstallmentFormSet(request.POST, instance=course)
        if installment_formset.is_valid():
            installment_formset.save()
            return HttpResponseRedirect(reverse('product:course_detail', args=[course.batch.pk]))

    context = {
        "installment_formset": installment_formset,
        'form_url': reverse_lazy('product:add_installments', args=[course.pk]),
        "type": "add",
        "course": course,
    }
    return render(request, "product/installments.html", context)


@login_required
def source_summary_report(request):
    products = Product.objects.annotate(total_count=Count('enquiry_courses__enquiry__my_courses'))
    sources = Campaign.objects.annotate(total_sources=Count('enquiry_campaign__enquiry__my_courses'))
    leads = sources.aggregate(total_leads=Sum('total_sources'))
    context = {
        'sources': sources,
        'leads': leads,
        'products': products

    }

    return render(request, "product/source_summary_report.html", context)


@login_required
def add_batch(request, pk):
    batch_form = BatchForm(request.POST)
    if batch_form.is_valid():
        course = get_object_or_404(Batch, pk=pk)
        batch = batch_form.save(commit=False)
        batch.batch = course
        batch.save()
    return HttpResponseRedirect(reverse('product:course_detail', args=[pk]))


@login_required
def course_detail(request, pk):
    course = Batch.objects.get(id=pk)
    batch_form = BatchForm()
    context = {
        "course": course,
        "form": batch_form,

    }
    return render(request, "product/course_detail.html", context)


@login_required
def edit_batch(request, pk):
    batch = Course.objects.get(id=pk)
    form = BatchForm(request.POST or None, instance=batch)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product:course_detail', args=[batch.batch.id]))
    context = {
        "form": form,
        "type": "edit",
        "batch": batch

    }
    return render(request, 'product/edit_batch.html', context)


@login_required
@group_required('front office admin')
def delete_batch(request, pk):
    course = get_object_or_404(Course, pk=pk)
    if request.method == 'POST':
        if StudentCourse.objects.filter(course__pk=pk).count():
            messages.add_message(request, messages.INFO,
                                 'You cannot delete this course because you have students enrolled for this.')
        else:
            course.installments.all().delete()
            course.delete()

product/templates/product/add_certification.html
{% extends "erp_admin/base.html" %}
{% load static %}
{% block css %}

{% endblock css %}
{% block content %}
<div class="block">
    <a href="{{ request.META.HTTP_REFERER }}" class="pull-right"><i class="fa fa-times"></i></a>
    <div class="row" align="center">
        <h3>Certifications for {{course.name}} </h3>

    </div>
</div>

<div class="block">
    <div class="row show-grid">
        <div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Test Name</th>
                    <th>Edit</th>
                    <th>Delete</th>

                </tr>
                </thead>
                <tbody>
                {% for certificate in certifications %}
                <tr>
                    <td>
                        {{certificate.name}}
                    </td>
                    <td>
                        {{ certificate.test_name }}
                    </td>
                    <td>
                        <a href="{% url 'product:edit_certification' certificate.pk %}"><i class="fa fa-pencil"></i></a>
                    </td>
                    <td>
                        <a href="{% url 'product:delete_certification' certificate.pk %}"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <p align="right" style="padding-top:30px;">
                <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">Add Certifications <i
                        class="fa fa-plus"></i></button>
            </p>
        </div>
    </div>
</div>


<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog" role="document">
        <form action="{{ form.url }}" method="post" enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Add Certification</h4>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label">{{ form.name.label }}</label><span class="req">*{{ form.name.errors }}</span>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group">
                                {{ form.name }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label">{{ form.test_name.label }}</label><span class="req">*{{ form.test_name.errors }}</span>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group">
                                {{ form.test_name }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label">{{ form.header_image.label }}</label><span class="req">*{{ form.header_image.errors }}</span>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group">
                                {{ form.header_image }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary pull-right">Submit</button>
                </div>
            </div>

        </form>
    </div>
</div>

{% endblock content %}
{% block jsscript %}

{% endblock jsscript %}

product/templates/product/code_setting.html
{% extends "erp_admin/base.html" %}
{% load static %} 
{% block content %}

<div class="blank">
	 <div class="grid-form1">
	 	  <a href="{% url 'product:view_products' %}">Cancel</a>
  	       <h3 style="margin-top:20px;">Prefix</h3>
  	         <div class="tab-content">
						<div class="tab-pane active" id="horizontal-form">
							<form class="form-horizontal" id="code_setting" action="{% url 'product:code_settings' %}" method="post">{% csrf_token %}
							{{ code_form.non_field_errors }}
							{{ code_form.field_errors }}
							
								<div class="form-group">
									<label class="col-sm-2 control-label">Prefix</label>
									<div class="col-sm-8 code-input">{{ code_form.prefix.errors }}
										{{ code_form.prefix }}
									</div>
								</div>

								<div class="form-group">
									<label class="col-sm-2 control-label">Count</label>
									<div class="col-sm-8 code-input">{{ code_form.count_index.errors }}
										{{ code_form.count_index }}
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-2 control-label">Number Of Characters</label>
									<div class="col-sm-8 code-input">{{ code_form.no_of_characters.errors }}
										{{ code_form.no_of_characters }}
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-2 control-label">Program Code:</label>
									<div class="col-sm-8 code-input">
										<span id="code"></span>
									</div>
									
								</div>
								

								<div class="form-group">
									<div class="col-sm-8">
                						<button class="btn-primary btn">Submit</button>
                					</div>
                				</div>

								
							</form>
						</div>
					</div>
					
	</div>
</div>
{% endblock content %}
{% block jsscript %}
<script>
$(document).ready(function(){
	$("form#code_setting").on('input', function(e){
		var code = ""
		var prefix = $(this).find("#prefix").val()
		// console.log(prefix)
		if(prefix){
			code += prefix
			
			var no_of_characters = $(this).find("#no_of_characters").val()
			var count = $(this).find("#count_index").val() + ""
			
			function pad(num, size) {
			    var s = num+"";
			    while (s.length < size) s = "0" + s;
			    return s;
			}
			
			code += pad(count, no_of_characters)
			
			console.log(code)
		}
		$("#code").text(code)
	})
	$("form#code_setting").trigger('input')
})	
</script>



{% endblock jsscript %}

product/templates/product/course_detail.html
{% extends "erp_admin/base.html" %}
{% load static tz %}
{% get_current_timezone as TIME_ZONE %}
{% block head %}
<style>


.fabutton {
  background: none;
  padding: 0px;
  border: none;
}



</style>
{% endblock head %}
{% block content %}


<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Add Batch</h4>
            </div>
            <div class="modal-body">
                <form action="{% url 'product:add_batch' course.pk %}" method="post">
                    {% csrf_token %}

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{ form.duration.label }}<span class="req">*</span></label>
                            {{ form.duration }}
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{form.time.label}}<span class="req">*</span></label>
                            {{form.time }}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{form.start_date.label}}<span class="req">*</span></label>
                            {{form.start_date }}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{form.total_fee.label}}<span class="req">*</span></label>
                            {{form.total_fee }}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{form.course_fee.label}}</label>
                            {{form.course_fee }}
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <button type="submit" class="btn btn-primary pull-right">Submit</button>
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>


<div class="block">
    <a href="{{ request.META.HTTP_REFERER }}" class="pull-right"><i class="fa fa-times"></i></a>
    <div class="row" align="center">
        <h3><a href="{% url 'product:detail' course.program.pk %}">{{course.program.name}}-{{ course.name}}</a></h3>
    </div>
</div>


<div class="batch_block">
    <div class="block">
        <div class="row show-grid">
            <div>
                <h3 style="text-align: center; font-size: 20px; color:black;">Batches</h3>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Course</th>
                        <th>Code</th>
                        <th>Duration</th>
                        <th>Time</th>
                        <th>Start Date</th>
                        <th colspan="2">Course Fee</th>
                        <th>Edit</th>
                        <th>Delete</th>
                        <th>Installments</th>
                        <th>Subjects</th>

                    </tr>

                    </thead>
                    <tbody>
                    {% for batch in course.batches.all %}
                    <tr>
                        <td>
                            {{batch.batch.name}}
                        </td>
                        <td>
                            {{batch.code}}
                        </td>

                        <td>
                            {{batch.get_duration_display}}
                        </td>
                        <td>
                            {{batch.get_time_display}}
                        </td>
                        <td>
                            {{batch.start_date}}
                        </td>
                        <td>
                            INR {{batch.total_fee}}
                        </td>
                        <td>
                           {% if batch.course_fee %} USD {{batch.course_fee}}{% endif %}
                        </td>
                        <td>
                            <a href="{% url 'product:edit_batch' batch.pk %}"><i class="fa fa-edit"></i></a>
                        </td>
                        <td>
                            <form method="post" action="{% url 'product:delete_batch' batch.pk %}"
                                  onsubmit="remove(this, event)">
                                {% csrf_token %}
                                <button type="submit" class="fabutton">
                                    <i class="fa fa-trash-o fa-fw"></i>
                                </button>
                            </form>
                        </td>
                        <td>

                            <a href="{% url 'product:add_installments' batch.pk %}"><i
                                    class="fa {% if batch.installments.count > 0  %}fa-edit{% else %}fa-plus{% endif %}"></i></a>

                        </td>

                         <td>

                            <a href="{% url 'product:add_subjects' batch.pk %}"><i
                                    class="fa {% if batch.installments.count > 0  %}fa-edit{% else %}fa-plus{% endif %}"></i></a>

                        </td>
                    </tr>
                    {% endfor %}


                    </tbody>
                </table>
                <p align="right" style="padding-top:30px;">
                    <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#filter-modal">Add Batch <i
                            class="fa fa-plus"></i></button>
                </p>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

{% block jsscript %}
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>

<script>
$(document).ready(function() {

    $('.tdate').daterangepicker({
        singleDatePicker: true,
        // calender_style: "picker_4",
        showDropdowns: true,
        locale: {
            format: 'YYYY-MM-DD',
                },
    }, function(start, end, label) {
        console.log(start.toISOString(), end.toISOString(), label);
    });
});




    function remove(form, e){
        e.preventDefault()
        if(confirm('Confirm Delete')){
            form.submit()
        }
    }



</script>

{% endblock jsscript %}