crm/urls.py
from django.conf.urls import url
from crm import campaign

app_name = "crm"

urlpatterns = [

    url(r'^campaign/create/$', campaign.campaign_create, name="campaign_create"),
    url(r'^campaign/list/$', campaign.campaign_list, name="campaign_list"),
    url(r'^campaign/(?P<pk>[^/]+)/detail/$', campaign.campaign_detail, name="campaign_detail"),
    url(r'^campaign/(?P<pk>[^/]+)/edit/$', campaign.campaign_edit, name="campaign_edit"),
    url(r'^campaign/(?P<pk>[^/]+)/list_products/$', campaign.products, name="products"),


]

expense/urls.py
from django.conf.urls import url, include
# from expense.bill.urls import urlpatterns as bill_patterns
from . import views, api

app_name = 'expense'

urlpatterns = [

    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^expenses/$', views.expense_index, name='expense_index'),
    url(r'^expense/(?P<pk>[^/]+)/edit/$', views.edit_Expense, name='edit_Expense'),
    url(r'^expense/create/$', views.expense_create, name='expense_create'),
    url(r'^incomes/$', views.income_index, name='income_index'),
    url(r'^income/(?P<pk>[^/]+)/edit/$', views.edit_income, name='edit_income'),
    url(r'^income/create/$', views.income_create, name='income_create'),
    url(r'^expense_income/report/$', views.expense_income_report, name='expense_income_report'),
    url(r'^account/report/$', views.account_report, name='account_report'),
    url(r'^expense_income/dashboard/$', views.report_dash, name='report_dash'),
    url(r'^account/create/$', views.account_create, name='account_create'),
    url(r'^account/list/$', views.account_list, name='account_list'),
    url(r'^transaction/report/$', views.transaction_report, name='transaction_report'),
    url(r'cash/breakup/report/$', views.cash_breakup_report, name='cash_breakup_report'),
    url(r'cash/received/report/$', views.cash_received_report, name='cash_received_report'),
    url(r'income/received/report/$', views.income_received_report, name='income_received_report'),

    url(r'^account/(?P<pk>[^/]+)/edit/$', views.account_edit, name='account_edit'),
    url(r'^account/undeposited_fund_create/$', views.undeposited_fund_create, name='undeposited_fund_create'),

]

expense/models.py
from django.db import models
from erp_core.models import ErpAbstractBaseModel
from django.core.validators import MinValueValidator
from student.models import StudentInstallment


class ExpenseType(ErpAbstractBaseModel):
    name = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class IncomeType(ErpAbstractBaseModel):
    name = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class Expense(ErpAbstractBaseModel):
    expense_type = models.ForeignKey(ExpenseType, null=True, blank=True)
    income_type = models.ForeignKey(IncomeType, null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    amount = models.DecimalField(max_digits=20, decimal_places=2, validators=[MinValueValidator(0)])
    income_or_expense = models.BooleanField(default=True)
    date = models.DateField(null=True, blank=True)
    voucher_number = models.CharField(max_length=200, blank=True)
    installment = models.ForeignKey(StudentInstallment,null=True,blank=True)

    def __str__(self):
        if self.expense_type:
            return str(self.expense_type) + "-" + str(self.date) + "-" + str(self.amount)
        else:
            return str(self.income_type) + "-" + str(self.date) + "-" + str(self.amount)






class AccountHead(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Account(ErpAbstractBaseModel):
    head = models.ForeignKey(AccountHead,related_name="accounts")
    description = models.CharField(max_length=255, null=True, blank=True)
    amount = models.DecimalField(max_digits=20, decimal_places=2, validators=[MinValueValidator(0)])
    date = models.DateField()

expense/views.py
import re
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models.functions import ExtractMonth

from student.models import StudentPayment
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy
from erp_core.pagination import paginate
import datetime
from django.forms import modelformset_factory
from .models import *
from .filters import *
from django.db.models import Sum, Count
from datetime import date, timedelta
from django.db.models.functions import TruncDay
from crm.models import Campaign


# # def add_SalesReimbursement(request, pk):
# #     user = request.user.employee
# #     form = SalesReimbursementForm(
# #         request.POST or None, request.FILES or None, current_user=user)
# #     if request.method == "POST":
# #         if form.is_valid():
# #             salesreimbursementExpenseConfig = form.save(commit=False)
# #             salesreimbursement.employee = get_object_or_404(Employee, id=pk)
# #             salesreimbursement.save()
# #             return HttpResponseRedirect(reverse('expense:view_SalesReimbursement', args=[pk]))
# #     context = {
# #         "form": form,
# #         'form_url': reverse_lazy('expense:add_SalesReimbursement', args=[pk]),
# #         "pk": pk,
# #         "type": "add"
# #     }
# #     return render(request, 'SalesReimbursement/add_SalesReimbursement.html', context)


# # def view_SalesReimbursement(request, pk):
# #     salesreimbursements = SalesReimbursement.objects.filter(employee_id=pk).order_by("-created_at")
# #     salesreimbursements, pagination = paginate(request, queryset=salesreimbursements, per_page=10, default=True)
# #     context = {
# #         "salesreimbursements": salesreimbursements,
# #         "pk": pk,
# #         'pagination': pagination
# #     }
# #     return render(request, 'SalesReimbursement/view_SalesReimbursement.html', context)


# # def edit_SalesReimbursement(request, pk, salesreimbursement_pk):

# #     # target = get_object_or_404(Targets, id=target_pk)
# #     user = request.user.employee
# #     salesreimbursement = SalesReimbursement.objects.get(
# #         id=salesreimbursement_pk)
# #     form = SalesReimbursementForm(
# #         request.POST or None, request.FILES or None, instance=salesreimbursement, current_user=user)
# #     if request.method == "POST":
# #         form.save()
# #         return HttpResponseRedirect(reverse('expense:view_SalesReimbursement', args=[pk]))
# #     context = {
# #         "form": form,
# #         'form_url': reverse_lazy('expense:edit_SalesReimbursement', args=[pk, salesreimbursement_pk]),
# #         "pk": pk,
# #         "salesreimbursement_pk": salesreimbursement_pk,
# #         "type": "edit"
# #     }
# #     return render(request, 'SalesReimbursement/add_SalesReimbursement.html', context)


# # def detail(request, pk):
# #     # quotation = get_object_or_404(Quotation, id=pk)
# #     salesreimbursements = SalesReimbursement.objects.get(id=pk)
# #     context = {
# #         "salesreimbursement": salesreimbursements,
# #         "pk": pk
# #     }
# #     return render(request, "SalesReimbursement/detail.html", context)


# # def approval_SalesReimbursement(request, pk):
# #     date = datetime.datetime.now()

# #     salesreimbursement = SalesReimbursement.objects.get(id=pk)
# #     if salesreimbursement.employee.reporting_officer == request.user.employee:
# #         salesreimbursement.approved_by = request.user.employee
# #         salesreimbursement.approved_date = date

# #         salesreimbursement.save()

# #         month_year = date.strftime("%B %Y")

# #         try:
# #             salary = MonthlySalary.objects.get(paid=False, employee=request.user.employee, month_year=month_year)
# #         except Exception as e:
# #             messages.add_message(request, messages.INFO, e)
# #             return HttpResponseRedirect(reverse('expense:detail', args=[pk]))
# #         salary.sales_reimbursement = salary.sales_reimbursement + salesreimbursement.amount
# #         salary.amount = salary.amount + salesreimbursement.amount
# #         salary.save()

# #     else:
# #         # messages.info(request, 'No Permission to approve')
# #         messages.add_message(request, messages.INFO, 'No Permission to approve')
# #     return HttpResponseRedirect(reverse('expense:detail', args=[pk]))


# # def view_approvalSalesReimbursement(request):
# #     salesreimbursements = SalesReimbursement.objects.filter(
# #         employee__reporting_officer=request.user.employee).distinct().order_by("-created_at")
# #     salesreimbursements, pagination = paginate(request, queryset=salesreimbursements, per_page=20, default=True)
# #     context = {
# #         "salesreimbursements": salesreimbursements,
# #         # "pk": pk,
# #         'pagination': pagination
# #     }
# #     return render(request, 'SalesReimbursement/view_SalesReimbursement.html', context)


# def record_expense_create(request, payee_type):

#     expense_form = ExpenseForm(request.POST or None, request.FILES or None)
#     payee_form = PayeeForm(request.POST or None, payee_type=payee_type)

#     if request.method == "POST":
#         if expense_form.is_valid() and payee_form.is_valid():
#             expense = expense_form.save(commit=False)
#             expense.payee = payee_form.cleaned_data['payee']
#             expense.save()
#             expense_form.save_m2m()
#             return HttpResponseRedirect(reverse('expense:view_expense', args=[expense.pk]))
#     context = {
#         "expense_form": expense_form,
#         'form_url': reverse_lazy('expense:record_expense_create', args=[payee_type]),
#         "type": "add",
#         "payee_form": payee_form,
#     }
#     return render(request, 'expense/record_expense_create.html', context)


# def bulk_expense_create(request, payee_type):

#     ExpenseFormSet = modelformset_factory(Expense, form=ExpenseFormsetForm, extra=0, min_num=2, max_num=100, can_delete=True)
#     expense_formset = ExpenseFormSet(queryset=Expense.objects.none())
#     payee_form = PayeeForm(request.POST or None, payee_type=payee_type)

#     if request.method == "POST":
#         expense_formset = ExpenseFormSet(request.POST)
#         if expense_formset.is_valid() and payee_form.is_valid():
#             # expense.payee = payee_form.cleaned_data['payee']
#             expenses = expense_formset.save(commit=False)
#             for expense in expenses:
#                 expense.payee = payee_form.cleaned_data['payee']
#                 expense.save()

#             return HttpResponseRedirect(reverse('expense:index'))

#     context = {
#         "expense_formset": expense_formset,
#         'form_url': reverse_lazy('expense:bulk_expense_create', args=[payee_type]),
#         "type": "add",
#         "payee_form": payee_form,
#     }
#     return render(request, 'expense/bulk_expense_create.html', context)


# def index(request, payee_type=None):

#     f = ExpenseFilter(request.GET, request=request, queryset=Expense.objects.all().order_by("-created_at"))
#     # expenses = Expense.objects.all().order_by("-created_at")

#     expenses, pagination = paginate(request, queryset=f.qs, per_page=10, default=True)
#     # print("expenses...........", expenses)
#     context = {
#         'expenses': f.qs,
#         'pagination': pagination,
#         'filter': f,
#     }

#     return render(request, "expense/list.html", context)


# def view_expense(request, pk):
#     expense = Expense.objects.get(id=pk)
#     context = {
#         "expense": expense,
#         "pk": pk
#     }
#     return render(request, "expense/details.html", context)


# def edit_Expense(request, pk):
#     expense = Expense.objects.get(id=pk)
#     expense_form = ExpenseForm(request.POST or None, request.FILES or None, instance=expense)
#     if request.method == "POST":
#         expense_form.save()
#         return HttpResponseRedirect(reverse('expense:view_expense', args=[pk]))
#     context = {
#         "expense_form": expense_form,
#         "expense": expense,
#         'form_url': reverse_lazy('expense:edit_Expense', args=[pk]),
#         "pk": pk,
#         "type": "edit"
#     }
#     return render(request, 'expense/record_expense_create.html', context)


# def dashboard(request):
#     return render(request, "expense/dashboard.html")


# def expense_type_list(request):
#     expense_name = request.GET.get('expense_name', False)
#     if expense_name:
#         expense = TypeOfExpense.objects.filter(
#             name__icontains=expense_name
#         ).annotate(
#             text=F('name')
#         ).values('id', 'name')

#         return JsonResponse(list(expense), safe=False)
#     return JsonResponse(list(), safe=False)


# def delete(request, pk):
#     if request.method == "POST":
#         expense = get_object_or_404(Expense, id=pk)
#         expense.delete()
#     return HttpResponseRedirect(reverse('expense:index'))


# def supplier_or_vendor(request, bulk=False):
#     form = ExpenserForm(request.POST or None)
#     if bulk:
#         form_url = reverse('expense:bulk_supplier_or_vendor')
#     else:
#         form_url = reverse('expense:supplier_or_vendor')

#     if request.method == 'POST':
#         if form.is_valid():
#             payee_type = form.cleaned_data['payee_type']
#             if bulk:
#                 return redirect(reverse("expense:bulk_expense_create", args=[payee_type]))
#             else:
#                 return redirect(reverse("expense:record_expense_create", args=[payee_type]))

#     context = {
#         'form': form,
#         'form_url': form_url,
#     }
#     return render(request, "expense/supplier_or_vendor.html", context)

@login_required
def dashboard(request):
    return render(request, "expense/dashboard.html")


@login_required

expense/templates/expense/account_create.html
{% extends "erp_admin/base.html" %}
{% load static %} 
{% block css %}

{% endblock css %}
{% block content %}

<div class="blank">
	<div class="grid-form1">
		<div class="row">
		 	<div class="col-sm-12 col-xs-12" align="right">
		 		
			</div>
		 	
		 	<div class="col-sm-12 col-xs-12">
		 			<h3><mark>Current Balance : <span id="current_bal">{{dif}}</span></mark></h3>
		 	</div>
		</div>
	 	
        <div class="tab-content">
			<div class="tab-pane active" id="horizontal-form">
			<form class="form-horizontal" action="{{ form_url }}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
					{{ account_form.non_field_errors }}
					{{ account_form.field_errors }}
					
					<div class="exp">
						<div class="table-responsive">
							<table class="table table-responsive" id="tablespan">
								<thead>
									<th>Date</th>
									<th>Head</th>
									<th>Amount</th>
									<th>Description</th>
								
								</thead>
								
								<tbody>
									<td>{{ account_form.date }}{{ account_form.date.errors }}</td>
									<td>{{ account_form.head }}{{ account_form.head.errors }}</td>
									<td>{{ account_form.amount }}{{ account_form.amount.errors }}</td>
									<td>{{ account_form.description }}{{ account_form.description.errors }}</td>
							
								</tbody>
							</table>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-12" style="padding-left:30px;">
    						<button class="btn-primary btn pull-right" type="submit">Submit</button>
    					</div>
    				</div>			
				</form>
			</div>
		</div>	
	</div>
</div>
{% endblock content %}
{% block jsscript %}

<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>

<script>
      $(document).ready(function() {
        var $date_inputs = $('.tdate')
	    var date_format = 'YYYY-MM-DD';
	    $date_inputs.daterangepicker({
	        singleDatePicker: true,
        autoUpdateInput: false,
        // minDate:new Date(),
        // timePicker: true,
        // timePicker24Hour: false,
        autoApply: true,
        showDropdowns: true,
        locale: {
            format: date_format,
        },
	        // calender_style: "picker_4",
	    }, function(start, end, label) {
	        console.log(start.toISOString(), end.toISOString(), label);
	    });

	    $date_inputs.on('apply.daterangepicker', function(ev, picker) {
	        $(this).val(picker.startDate.format('YYYY-MM-DD'));
	    });

	    $date_inputs.on('cancel.daterangepicker', function(ev, picker) {
	        $(this).val('');
	    });

	    $( "#id_amount" ).change(function() {
			var amount = $(this).val()
			var current_val = $('#current_bal').text()
			console.log("am",amount)
			console.log("cr",current_val)
			if(parseFloat(amount) > parseFloat(current_val)){
				alert("Amount should be less than current balance")
				 $(this).val(0)
				$('#current_bal').text({{dif}})


			}
			else{
				var balance =current_val-amount
				$('#current_bal').text(balance)
				
			}
			});



      });
      

     
</script>


{% endblock jsscript %}

expense/templates/expense/dashboard.html
{% extends "erp_admin/base.html" %} {% load guardian_tags %} {% block content %}
{% load staticfiles %}
{% block head %}
<link href="{% static 'css/box_style.css' %}" rel='stylesheet' type='text/css' />

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">

{% endblock head %}
<div class="blank">
    <div class="blank-page">
        <div class="row show-grid" style="margin-bottom:300px;">
            <div class="col-sm-12 col-md-12 col-xs-12">
                <h2>Expense</h2>
                <div class="row" style="margin-top:30px;">

                    <div class="col-sm-12 col-md-4  col-xs-12">

                     <div class="border_style bg2" align="center">
                        
                            <a href="{% url 'expense:employee_or_vehicle' %}">
                            <span class="white">Employee/Vehicle</span>
                            <div>
                            <span class="white"><i class="fa fa-plus fa-2x"></i></span>
                            </div>
                            </a>
                        </div>
                    
                    </div>
                    <div class="col-sm-12 col-md-4 col-xs-12">
                        <div class="border_style bg1" align="center">
                            <a href="{% url 'expense:other_expense_list' %}">
                            <span class="white">Other Expense</span>
                            <div>
                            <span class="white" style="margin-top:3px;"><i class="fa fa-eye fa-2x"></i></span>
                            </div>
                            </a>
                        </div>
                     
                    </div>

                    <div class="col-sm-12 col-md-4 col-xs-12">
                        <div class="border_style bg4" align="center">
                            <a href="{% url 'expense:other_income_list' %}">
                            <span class="white">Other Income</span>
                            <div>
                            <span class="white" style="margin-top:3px;"><i class="fa fa-eye fa-2x"></i></span>
                            </div>
                            </a>
                        </div>
                     
                    </div>
                    
                    <div class="col-sm-12 col-md-4  col-xs-12">

                      <div class="border_style bg3" align="center">
                            <a href="{% url 'expense:expense_index' %}" style="text-decoration:none;">
                            <span class="white">View Employee/Vehicle Expense/Income </span>
                            <div>
                            <span class="white"><i class="fa fa-eye fa-2x"></i></span>
                            </div>
                            </a>
                        </div>
                    
                     
                    </div>
                    <div class="col-sm-12 col-md-4  col-xs-12">

                      <div class="border_style bg7" align="center">
                            <a href="{% url 'expense:expense_income_report' %}" style="text-decoration:none;">
                            <span class="white">Report</span>
                            <div>
                            <span class="white"><i class="fa fa-list fa-2x"></i></span>
                            </div>
                            </a>
                        </div>
                    
                     
                    </div>
                   
                </div>
<!--
                <div class="row">
                    <div class="col-sm-12 col-md-4  col-xs-12">

                        <div class="border_style bg5" align="center">
                            <a href="" style="text-decoration:none;">
                            <span class="white">Bill</span>
                            <div>
                            <span class="white"><i class="fa fa-money fa-2x"></i></span>
                            </div>
                            </a>
                        </div>
                     
                    </div>
                     <div class="col-sm-12 col-md-4 col-xs-12">
                        <div class="border_style bg1" align="center">
                            <a href="" style="text-decoration:none;">
                            <span class="white">Record Electricity Bill</span>
                            <div>
                            <span class="white" style="margin-top:3px;"><i class="fa fa-plus fa-2x"></i></span>
                            </div>
                            </a>
                        </div>
                     
                    </div>

                </div>
-->

            </div>
        </div>
        
    </div>
</div>


{% endblock content %}

expense/templates/expense/employee_or_vehicle.html
<!--Last Modified By:REMYA M S-->
{% extends "erp_admin/base.html" %}
{% load static %}
{% block content %}

<div class="blank">
    <div class="grid-form1">
        <a href="{% url 'expense:expense_index' %}">Cancel</a>
        <h3 style="margin-top:20px;">Employee/Vehicle</h3>
        <div class="tab-content">
            <div class="tab-pane active" id="horizontal-form">
                <form class="form-horizontal" action="{{ form_url }}" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}

                    <div class="form-group">
                        <label for="subject" class="col-sm-2 control-label">{{ form.payee_type.label }}</label>
                        <div class="col-sm-4">{{ form.payee_type.errors }} {{ form.payee_type }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-4">
                            <button class="btn-primary btn">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>

    </div>
</div>
{% endblock content %}
{% block jsscript %}
{% endblock jsscript %}

expense/templates/expense/income_list.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static %}
{% block head %}
<style type="text/css">

</style>
{% endblock head %}
{% block content %}

<!-- Modal -->
<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Filters</h4>
      </div>
      <div class="modal-body">
        <form action="" method="get">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Income Type</label>
                        {{ filter.form.income_type }}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">{{ filter.form.amount.label }}</label>
                        {{ filter.form.amount }}
                    </div>
                </div>
                 <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Date & Month</label>
                        {{ filter.form.date }}
                    </div>
                </div>
            </div>
            
           
            
            <div class="row">
                <div class="pull-left" style="padding-left:10px;">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                <div class="clearfix"></div>

            </div>

        </form>
      </div>
    </div>
  </div>
</div>


    <div class="content-main">
        <div class="block">
            <div class="row">
                <div class="col-sm-12 col-xs-12" style="padding-left:30px;">
                   
                </div>
            </div>
            <div class="row show-grid">
                <div class="col-sm-6">
                    <h3>
                        Income
                        <a href="{% url 'expense:income_create' %}" class="btn btn-link">
                              <i class="fa fa-plus-square-o fa-2x"></i>
                        </a>
                    </h3>
                </div>
                <div class="col-sm-6">
                    <div class="pull-right">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#filter-modal">
                          <i class="fa fa-filter"></i> Filters
                        </button>
                        <a class="btn btn-primary btn-sm" href="{% url 'expense:income_index' %}">
                         <i class="fa fa-refresh"></i> Refresh
                        </a>
                    </div>
                </div>                         
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Date</th>
                                    <th>Type</th>
                                    <th>Amount</th>
                                    <th>Edit</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for expense in expenses %}
                                <tr>
                                    <td scope="row">{{ forloop.counter }}</td>
                                    <td>{{ expense.date|date:'d/m/y' }}</td>
                                    <td>
                                        {{ expense.income_type }}

                                    </td>
                                    
                                  
                                    <td>
                                        <i class="fa fa-inr"></i> {{ expense.amount }}
                                    </td>
                                    
                                    <td>
                                       
                                        <a href="{% url 'expense:edit_income' expense.pk %}">
                                            <i class="fa fa-edit fa-1x"></i>
                                        </a>
                                    </td>
                                    
                                </tr>
                                {% empty %}
                                <tr><td colspan="8">No Income</td></tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <div id="pagination">
                        {{pagination|safe}}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block jsscript %}
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>
<script>
$(document).ready(function(){
    $('.tdate').daterangepicker({
          singleDatePicker: true,
          // timePicker: true,
          // calender_style: "picker_4",
          showDropdowns: true,
          locale: {
                format: 'YYYY-MM-DD',
                },


        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
    });
    $('[data-toggle="tooltip"]').tooltip();

    $("#pagination a").click(function(e){
        e.preventDefault()
        page_string = this.href.slice(this.href.indexOf("?") + 1)
        
        var query_string = ""   
        var search_query = window.location.search
        var query_obj = {}
        if(search_query){
            if(search_query.indexOf('?') > -1)
                search_query = search_query.substr(1)
            
            var searchQueryStrings = [search_query]
            if(search_query.indexOf('&') > -1)
                searchQueryStrings = search_query.split('&')
            
            searchQueryStrings.forEach(qs => {
                var query_array = qs.split('=')
                query_obj[query_array[0]] = query_array[1]
            })

        }
        
        query_obj['page'] = page_string.split('=')[1]
        for(var k in query_obj){
            query_string += k + '=' + query_obj[k] + '&'
        }
        
        // console.log(query_string, query_obj, window.location)
        window.location = window.location.pathname + "?" + query_string.slice(0, -1)
    })
    var format = 'YYYY-MM-DD'
    function cb(start, end) {
        $('#date span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        $("#id_date_0").val(start.format(format));
        $("#id_date_1").val(end.format(format));  
    }

    $('#filter-modal').on('shown.bs.modal', function () {
        console.log(moment($("#id_date_0").val()))
        var start_date = $("#id_date_0").val() ? moment($("#id_date_0").val()) : moment().subtract(29, 'days')
        var end_date = $("#id_date_1").val() ? moment($("#id_date_1").val()) : moment()
    
        $('#date').daterangepicker({
            startDate: start_date,
            endDate: end_date,
            showDropdowns: true,
            locale: {
                format: format,
            },
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
        cb(start_date, end_date)

    })

    function remove(form, e){
        e.preventDefault()
        if(confirm('Confirm Delete')){
            form.submit()
        }
    }

});
</script>
{% endblock jsscript %}